# Generated by Django 5.2.4 on 2025-08-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar_card_no', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=21, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('upload_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Tax', 'Tax'), ('Registration', 'Registration'), ('Consultancy', 'Consultancy'), ('Filing', 'Filing'), ('Legal', 'Legal')], max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='lead.lead')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.service')),
            ],
            options={
                'unique_together': {('lead', 'service')},
            },
        ),
    ]
