# Generated by Django 5.2.4 on 2025-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('vendor', 'Vendor'), ('other', 'Other')], default='customer', max_length=10),
        ),
    ]
