# Generated by Django 5.2.4 on 2025-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
