# Generated by Django 5.2.4 on 2025-08-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by customer so far.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
