# Generated by Django 5.2.4 on 2025-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_task_amount_paid_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='lead',
            name='uploaded_documents_json',
            field=models.JSONField(blank=True, help_text='Stores multiple uploaded documents as JSON', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial Paid')], default='pending', max_length=10),
        ),
    ]
