# Generated by Django 5.2.4 on 2025-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_task_options_lead_uploaded_documents_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='uploaded_documents_json',
        ),
        migrations.AddField(
            model_name='lead',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
