# Generated by Django 5.2.4 on 2025-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_remove_lead_uploaded_documents_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('vendor', 'Vendor'), ('other', 'Other')], default='lead', max_length=10),
        ),
    ]
