# Generated by Django 5.2.4 on 2025-08-09 09:44

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_remove_lead_uploaded_documents_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='document_name',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
